config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  devise_for :users
  # devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {
  #   registrations: 'users/registrations'
  # }

  scope ActiveStorage.routes_prefix do
    get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  end

  get '/', to: 'home#index', as: 'home_page'

  get '/projects', to: 'project#index', as: 'projects_list'
  get '/projects/create', to: 'project#new', as: 'new_project'
  post '/projects/create', to: 'project#create', as: 'create_project'
  get '/projects/view/:uuid', to: 'project#view', as: 'view_project'
  get '/projects/view/:uuid/updates', to: 'project#updates', as: 'view_project_updates'
  get '/projects/edit/:uuid', to: 'project#edit', as: 'edit_project'
  patch '/projects/edit/:uuid', to: 'project#update', as: 'update_project'

  get '/scopes', to: 'scope#index', as: 'scopes_list'
  get '/scopes/create/:uuid', to: 'scope#new', as: 'new_scope'
  post '/scopes/create/:uuid', to: 'scope#create', as: 'create_scope'
  get '/scopes/view/:uuid', to: 'scope#view', as: 'view_scope'
  get '/scopes/view/:uuid/updates', to: 'scope#updates', as: 'view_scope_updates'
  get '/scopes/edit/:uuid', to: 'scope#edit', as: 'edit_scope'
  patch '/scopes/edit/:uuid', to: 'scope#update', as: 'update_scope'

  get '/issues', to: 'issue#index', as: 'issues_list'
  get '/issues/create/(:uuid)', to: 'issue#new', as: 'new_issue'
  post '/issues/create/(:uuid)', to: 'issue#create', as: 'create_issue'
  get '/issues/view/:uuid', to: 'issue#view', as: 'view_issue'
  get '/issues/view/:uuid/updates', to: 'issue#updates', as: 'view_issue_updates'
  get '/issues/edit/:uuid', to: 'issue#edit', as: 'edit_issue'
  patch '/issues/edit/:uuid', to: 'issue#update', as: 'update_issue'
  delete '/issues/a/delete/:uuid/:id', to: 'issue#delete_file', as: 'issue_delete_attachment'

  post '/comments/create/:uuid', to: 'comment#create', as: 'create_comment'
  
  get '/admin', to: 'admin/general#index', as: 'admin_general_page'
  patch '/admin/settings', to: 'admin/general#update', as: 'update_settings'
  get '/admin/users', to: 'admin/users#index', as: 'admin_users_page'
  get '/admin/users/create', to: 'admin/users#new', as: 'new_user'
  post '/admin/users/create', to: 'admin/users#create', as: 'create_user'
  get '/admin/users/edit/:uuid', to: 'admin/users#edit', as: 'edit_user'
  post '/admin/users/edit/:uuid', to: 'admin/users#update', as: 'update_user'

  get '/settings', to: 'settings#index', as: 'settings_page'
  get '/help', to: 'help#index', as: 'help_page'

end

app/models/scope.rb
class Scope < ApplicationRecord
	audited

	belongs_to :project
	belongs_to :user
	has_many :issue

	before_create :set_defaults

	validates :title, presence: true
	validates :version, presence: true
	
	private
	  def set_defaults
	    self.uuid = SecureRandom.uuid
	  end
end

app/controllers/scope_controller.rb
class ScopeController < ApplicationController

	before_action :authenticate_user!
	before_action :set_record, only: [:view, :edit, :update, :updates, :delete]

	def index
		if !params[:search].blank?
			@parameter = params[:search].downcase
			@records = Scope.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
		else
			@records = Scope.all()
		end
	end

	def view
		if @record.issue.length > 0
			@pagy, @records = pagy(@record.issue.order('id desc'), items: 2)
		end
	end

	def updates
		@updates = @record.audits.reorder(id: :desc)
	end

	def new
		@project = Project.find_by(uuid: params[:uuid])

		if @project.nil?
			redirect_to root_path
		else
			@record = Scope.new
			@record.user_id = current_user.id
			@record.project_id = @project.id
		end
	end

	def create
		@project = Project.find_by(uuid: params[:uuid])

		if @project.nil?
			redirect_to root_path
		else

			@record = Scope.new(request_params)
			@record.project_id = @project.id
			@record.user_id = current_user.id

			if @record.valid?
				@record.save!
				redirect_to(view_scope_path(@record.uuid), notice: 'Successfully created.' )
			else
				render :new
			end
		end
	end

	def edit
	end

	def update
		if @record.update(request_params)
			redirect_to view_scope_path(@record.uuid), notice: 'Updated successfully.'
		else
			redirect_to view_scope_path(@record.uuid), notice: 'Unable to save, try again.'
		end
	end

	def delete
		if current_user.id == @record.user_id || current_user.admin?
			@record.destroy
			if current_user.admin?
				redirect_back(fallback_location: root_path, notice: 'Deleted successfully.')
			else
				redirect_to({:controller => "home", :action => "index"}, notice: 'Deleted successfully.' )
			end
		else
			redirect_to({:action => "show", :uuid => @record.uuid}, notice: 'Unable to delete.' )
		end
	end

	private
	def set_record
		@record = Scope.find_by(uuid: params[:uuid])
		if @record.nil?
			redirect_to(root_path, notice: "No record found!")
		end
	end

	def request_params
		params.require(:scope).permit(:title, :version, :project, :description)
	end

end

app/helpers/scope_helper.rb
module ScopeHelper
end

app/views/scope/_tab.html.erb
<div class="columns">
  <div class="column">
    <div class="tabs">
      <ul>
        <li class="<%= current(view_scope_path) %>"><%= link_to "Details", view_scope_path, class: "" %></li>
        <li class="<%= current(view_scope_updates_path) %>"><%= link_to "Updates", view_scope_updates_path, class: "" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/scope/edit.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">Update scope</h4>
			<hr />
			<%= simple_form_for (@record), {url: edit_scope_path(@record.uuid)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>
			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :version, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />

			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined is-small" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Update scope", class:"button is-primary is-fullwidth is-small" %>
				</div>
			</div>
			<% end %>

			<br>
		</div>
	</div>
</section>

app/views/scope/index.html.erb
<div class="columns">
	<div class="column">
		<div class="columns">
			<div class="column">
				<div class="buttons">

				</div>
			</div>
		</div>
		<div class="columns">
			<div class="column">
				<% @records.each do |record| %>
					<%= record.description %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/scope/new.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">New scope</h4>
			<hr />
			<%= simple_form_for (@record), {url: create_scope_url(@project.uuid)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>
			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :version, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: true, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />

			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Add scope to the project", class:"button is-primary is-fullwidth" %>
				</div>
			</div>
			<% end %>

			<br>
		</div>
	</div>
</section>

app/views/scope/updates.html.erb
<div class="columns">
  <div class="column">
    <div class="columns">
      <div class="column">
        <%= render "/scope/tab" %>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <%= render "/layouts/updates" %>
      </div>
    </div>
  </div>
</div>

app/views/scope/view.html.erb
<div class="columns">
	<div class="column">

		<div class="columns">
			<div class="column">
				<%= render "/scope/tab" %>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<%= link_to new_issue_path(uuid: @record.uuid), class: "button is-primary is-outlined is-small"  do %>
					<%= fa_icon "pencil" %>&nbsp;New issue
				<% end %>
				<%= link_to edit_scope_path(@record.uuid), class: "button is-primary is-outlined is-small" do %>
					<%= fa_icon "pencil" %>&nbsp;Edit scope
				<% end %>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Details</p>
					</div>
					<div class="column is-5">
						<% if @record.issue.length > 0 %>
							<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
						<% end %>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<table class="table is-fullwidth is-striped is-bordered">
							<tbody>
								<tr>
									<td style="width: 25%">Title</td>
									<td><%= @record.title %></td>
								</tr>
								<tr>
									<td>Description</td>
									<td><%= @record.description %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<div class="columns">
							<div class="column">
								<p class="has-text-weight-semibold">Issues</p>
							</div>
							<div class="column is-5">
								<% if @record.issue.length > 0 %>
								<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
								<% end %>
							</div>
						</div>
						<% if @record.issue.length > 0 %>
						<div class="columns">
							<div class="column">
								<table class="table is-striped is-fullwidth is-bordered">
									<thead>
										<tr>
											<th style="width: 36px"></th>
											<th>Title</th>
											<th style="width: 36px"></th>
										</tr>
									</thead>
									<tbody>
										<% @records.each do |s| %>
										<tr>
											<td><%= fa_icon "folder" %></td>
											<td><%= s.title %></td>
											<td class="level-right">
												<%= link_to view_issue_path(s.uuid)  do %>
												<%= fa_icon "folder-open-o" %>
												<% end %>
											</td>
										</tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
						<% else %>
						<div class="columns">
							<div class="column">
								<h4>No issues.</h4>
							</div>
						</div>
						<% end %>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>