config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  devise_for :users
  # devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {
  #   registrations: 'users/registrations'
  # }

  scope ActiveStorage.routes_prefix do
    get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  end

  get '/', to: 'home#index', as: 'home_page'

  get '/projects', to: 'project#index', as: 'projects_list'
  get '/projects/create', to: 'project#new', as: 'new_project'
  post '/projects/create', to: 'project#create', as: 'create_project'
  get '/projects/view/:uuid', to: 'project#view', as: 'view_project'
  get '/projects/view/:uuid/updates', to: 'project#updates', as: 'view_project_updates'
  get '/projects/edit/:uuid', to: 'project#edit', as: 'edit_project'
  patch '/projects/edit/:uuid', to: 'project#update', as: 'update_project'

  get '/scopes', to: 'scope#index', as: 'scopes_list'
  get '/scopes/create/:uuid', to: 'scope#new', as: 'new_scope'
  post '/scopes/create/:uuid', to: 'scope#create', as: 'create_scope'
  get '/scopes/view/:uuid', to: 'scope#view', as: 'view_scope'
  get '/scopes/view/:uuid/updates', to: 'scope#updates', as: 'view_scope_updates'
  get '/scopes/edit/:uuid', to: 'scope#edit', as: 'edit_scope'
  patch '/scopes/edit/:uuid', to: 'scope#update', as: 'update_scope'

  get '/issues', to: 'issue#index', as: 'issues_list'
  get '/issues/create/(:uuid)', to: 'issue#new', as: 'new_issue'
  post '/issues/create/(:uuid)', to: 'issue#create', as: 'create_issue'
  get '/issues/view/:uuid', to: 'issue#view', as: 'view_issue'
  get '/issues/view/:uuid/updates', to: 'issue#updates', as: 'view_issue_updates'
  get '/issues/edit/:uuid', to: 'issue#edit', as: 'edit_issue'
  patch '/issues/edit/:uuid', to: 'issue#update', as: 'update_issue'
  delete '/issues/a/delete/:uuid/:id', to: 'issue#delete_file', as: 'issue_delete_attachment'

  post '/comments/create/:uuid', to: 'comment#create', as: 'create_comment'
  
  get '/admin', to: 'admin/general#index', as: 'admin_general_page'
  patch '/admin/settings', to: 'admin/general#update', as: 'update_settings'
  get '/admin/users', to: 'admin/users#index', as: 'admin_users_page'
  get '/admin/users/create', to: 'admin/users#new', as: 'new_user'
  post '/admin/users/create', to: 'admin/users#create', as: 'create_user'
  get '/admin/users/edit/:uuid', to: 'admin/users#edit', as: 'edit_user'
  post '/admin/users/edit/:uuid', to: 'admin/users#update', as: 'update_user'

  get '/settings', to: 'settings#index', as: 'settings_page'
  get '/help', to: 'help#index', as: 'help_page'

end

app/models/issue.rb
class Issue < ApplicationRecord
	audited
	enum status: [:open, :closed, :ongoing, :cancelled]
	enum severity: [:low, :medium, :high, :critical]

	belongs_to :scope
	belongs_to :user

	before_create :set_defaults

	validates :title, presence: true
	validates :severity, presence: true
	validates :description, presence: true

	has_many :comments
	has_many :tag
	has_many_attached :files

	scope :filter_by_status, -> (status) { where status: status }
	scope :filter_by_severity, -> (severity) { where severity: severity }
	scope :filter_by_title, -> (title) { where("title like ?", "%#{title}%") }
	scope :filter_by_scope, -> (scope) { joins(:scope).where('scopes.uuid = ?', scope) }

	def sequence_number
		return nil unless self.persisted?
		id_with_zeros = "%04d" % self.id
		"I#{self.created_at.year}#{self.created_at.month}#{self.created_at.day}#{id_with_zeros}"
	end

	def notify_slack
      SlackNotifier::CLIENT.ping "🎴 New report: #{self.title} \n https://bounty.pickme.lk/report/show/#{self.uuid}"
    end

	private
	def set_defaults
		self.status ||= :open
	    self.uuid = SecureRandom.uuid
	end

end

app/controllers/issue_controller.rb
class IssueController < ApplicationController

	before_action :authenticate_user!
	before_action :set_record, only: [:view, :edit, :update, :updates, :delete, :delete_file]

	def index
			query = Issue.where(nil)

			if !params[:status].blank?
				query = query.filter_by_status(params[:status]) if params[:status].present?
			end

			if !params[:severity].blank?
				query = query.filter_by_severity(params[:severity]) if params[:severity].present?
			end

			if !params[:scope].blank?
				query = query.filter_by_scope(params[:scope]) if params[:scope].present?
			end

			@open_records = query.where("status = 0").size
			@closed_records = query.where("status = 1").size
			@inprogress_records = query.where("status = 2").size
			@pagy, @records = pagy(query.order('id desc'), items: 5)

	end

	def view
		@pagy, @comments = pagy(@record.comments.order('id desc'), items: 3)

		@comment = Comment.new
		@comment.issue_id = @record.id
	end

	def updates
		@updates = @record.audits.reorder(id: :desc)
	end

	def new
		if !params[:uuid].nil?
			@scope = Scope.find_by(uuid: params[:uuid])

			@record = Issue.new
			@record.scope_id = @scope.id

			@scope_uuid = @scope.uuid
		else
			@record = Issue.new
			@scope_uuid = nil
		end
	end

	def create
			@record = Issue.new(request_params)
			if !params[:uuid].nil?
				@scope = Scope.find_by(uuid: params[:uuid])
				@record.scope_id = @scope.id
			end
			@record.user_id = current_user.id

			if @record.valid?
				@record.save!
				redirect_to(view_issue_path(@record.uuid), notice: 'Issue created successfully.' )
			else
				render :new
			end
	end

	def edit
	end

	def update
		if @record.update(request_params)
			redirect_to(view_issue_path(@record.uuid), notice: 'Updated successfully.' )
		else
			redirect_to edit_issue_path(@record.uuid)
		end
	end

	def delete
		if current_user.id == @record.user_id || current_user.admin?
			@record.destroy
			if current_user.admin?
				redirect_back(fallback_location: root_path, notice: 'Deleted successfully.')
			else
				redirect_to({:controller => "home", :action => "index"}, notice: 'Deleted successfully.' )
			end
		else
			redirect_to({:action => "show", :uuid => @record.uuid}, notice: 'Unable to delete.' )
		end
	end

	def delete_file
		file = ActiveStorage::Attachment.find(params[:id])
		file.purge
		redirect_to view_issue_path(@record.uuid), notice: 'Attachment deleted successfully.'
	end

	private
	def set_record
		@record = Issue.find_by(uuid: params[:uuid])
		if @record.nil?
			redirect_to(root_path, notice: "No record found!")
		end
	end

	def request_params
		params.require(:issue).permit(:title, :issue, :description, :solution, :score, :severity, :status, :scope_id, files: [])
	end

end

app/helpers/issue_helper.rb
module IssueHelper
end

app/views/issue/_comment.html.erb
<%= simple_form_for (comment), {url: create_comment_url(record.uuid)} do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :message, required: true, input_html: { rows: 3, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
    </div>
  </div>
  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= f.button :submit, "Comment", class:"button is-primary is-fullwidth is-small" %>
    </div>
  </div>
<% end %>

app/views/issue/_solution.html.erb
<%= simple_form_for (record), {url: add_solution_url(record.uuid), method: :patch} do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :solution, required: true, input_html: { rows: 3, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
    </div>
  </div>
  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= f.button :submit, "Solution", class:"button is-primary is-fullwidth is-small" %>
    </div>
  </div>
<% end %>

app/views/issue/_tab.html.erb
<div class="columns">
  <div class="column">
    <div class="tabs">
      <ul>
        <li class="<%= current(view_issue_path) %>"><%= link_to "Details", view_issue_path, class: "" %></li>
        <li class="<%= current(view_issue_updates_path) %>"><%= link_to "Updates", view_issue_updates_path, class: "" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/issue/edit.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">Edit issue <%= @record.sequence_number %></h4>
			<hr />
			<%= simple_form_for (@record), {url: update_issue_path(@record.uuid)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>

			<% if @scope_uuid.nil? %>
				<div class="field">
					<div class="control">
						<label class="label">Scope</label>
						<div class="select is-fullwidth">
							<%= f.input :scope_id, as: :select, collection: Scope.all.map{ |s| [s.id, s.title]}, input_html: { class: "select"}, label_method: :second, value_method: :first, label_html: { class: "label" }, error_html: { class: "help is-danger" }, wrapper: false, label: false %>
						</div>
					</div>
				</div>
			<% end %>
			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<label class="label">Severity</label>
					<div class="select is-fullwidth">
						<%= f.input :severity, as: :select, collection: Issue.severities.map {|key, value| [key, Issue.severities.key(value).capitalize]}, input_html: { class: "select"}, label_method: :second, value_method: :first, label_html: { class: "label" }, error_html: { class: "help is-danger" }, wrapper: false, label: false %>
					</div>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :score, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :solution, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :files,  as: :file, required: false, input_html: { class: "file", multiple: true }, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />
			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined is-small" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Update", class:"button is-primary is-fullwidth is-small" %>
				</div>
			</div>
			<% end %>

			<br>
		</div>
	</div>
</section>

app/views/issue/index.html.erb
<div class="columns">
	<div class="column">
		<div class="columns">
			<div class="column">
				<div class="buttons">

				</div>
			</div>
		</div>
		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Issues (<%= @records.length %>)</p>
					</div>
					<div class="column is-5">
						<% if @records.length > 0 %>
						<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
						<% end %>
					</div>
				</div>

				<form method="get" action="<%= issues_list_path %>">

					<div class="columns">
						<div class="column is-3">
							<input type="text" name="keyword" class="input is-small" placeholder="Search title.." />
						</div>
						<div class="column is-3">
							<div class="field">
								<div class="control">
									<div class="select is-fullwidth is-small">
										<select name="scope">
											<option value="">--</option>
											<% Scope.all.each do |s| %>
												<option value="<%= s[:uuid] %>" <% if params[:scope] == s[:uuid] %>selected<% end %>><%= s[:title] %></option>
											<% end %>
										</select>
										</div>
								</div>
							</div>
						</div>
						<div class="column is-2">
							<div class="field">
								<div class="control">
									<div class="select is-fullwidth is-small">
										<select name="severity">
											<option value="">--</option>
											<% Issue.severities.each do |s| %>
												<option value="<%= s[0] %>" <% if params[:severity] == s[0] %>selected<% end %>><%= s[0].capitalize %></option>
											<% end %>
										</select>
										</div>
								</div>
							</div>
						</div>

						<div class="column is-2">
							<div class="field">
								<div class="control">
									<div class="select is-fullwidth is-small">
										<select name="status">
											<option value="">--</option>
											<% Issue.statuses.each do |s| %>
												<option value="<%= s[0] %>" <% if params[:status] == s[0] %>selected<% end %>><%= s[0].capitalize %></option>
											<% end %>
										</select>
									</div>
								</div>
							</div>
						</div>

						<div class="column is-2">
							<div class="field">
								<div class="control">
									<button class="button is-small is-fullwidth">
										Filter
									</button>
								</div>
							</div>
						</div>

					</div>
				</form>


				<div class="columns">
					<div class="column">
						<div class="field is-grouped is-grouped-multiline">
							<div class="control">
								<div class="tags has-addons">
									<span class="tag is-dark">Open</span>
									<span class="tag is-info"><%= @open_records %></span>
								</div>
							</div>

							<div class="control">
								<div class="tags has-addons">
									<span class="tag is-dark">Closed</span>
									<span class="tag is-success"><%= @closed_records %></span>
								</div>
							</div>

							<div class="control">
								<div class="tags has-addons">
									<span class="tag is-dark">In progress</span>
									<span class="tag is-primary"><%= @inprogress_records %></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<table class="table is-striped is-fullwidth is-bordered">
							<thead>
								<tr>
									<th style="width: 36px"></th>
									<th>#</th>
									<th>Title</th>
									<th>Status</th>
									<th>Severity</th>
									<th style="width: 40px">Score</th>
									<th>Create at</th>
									<th style="width: 36px"></th>
								</tr>
							</thead>
							<tbody>
								<% if @records.length > 0 %>
								<% @records.each do |s| %>
								<tr>
									<td><%= fa_icon "folder" %></td>
									<td><%= s.sequence_number %></td>
									<td><%= s.title %></td>
									<td><%= s.status.capitalize %></td>
									<td><%= s.severity.capitalize %></td>
									<td><%= s.score %></td>
									<td><%= distance_of_time_in_words_to_now(s.created_at) %> ago</td>
									<td class="level-right">
										<%= link_to view_issue_path(s.uuid)  do %>
											<%= fa_icon "folder-open-o" %>
										<% end %>
									</td>
								</tr>
								<% end %>
								<% else %>
								<tr>
									<td colspan="7" class="has-text-centered">No records to show</td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/issue/new.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">New issue</h4>
			<hr />
			<%= simple_form_for (@record), {url: create_issue_path(@scope_uuid)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>

			<% if @scope_uuid.nil? %>
				<div class="field">
					<div class="control">
						<label class="label"><abbr title="required">*</abbr> Scope</label>
						<div class="select is-fullwidth">
							<%= f.input :scope_id, as: :select, collection: Scope.all.map{ |s| [s.id, s.title]}, input_html: { class: "select"}, label_method: :second, value_method: :first, label_html: { class: "label" }, error_html: { class: "help is-danger" }, wrapper: false, label: false, required: true %>
						</div>
					</div>
				</div>
			<% end %>


			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
				<div class="field">
					<div class="control">
						<label class="label"><abbr title="required">*</abbr> Severity</label>
						<div class="select is-fullwidth">
							<%= f.input :severity, as: :select, collection: Issue.severities.map {|key, value| [key, Issue.severities.key(value).capitalize]}, input_html: { class: "select"}, label_method: :second, value_method: :first, label_html: { class: "label" }, error_html: { class: "help is-danger" }, wrapper: false, label: false, required: true %>
						</div>
					</div>
				</div>
				<div class="field">
					<div class="control">
						<%= f.input :score, required: false, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
					</div>
				</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: true, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :solution, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :files,  as: :file, required: false, input_html: { class: "file", multiple: true }, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />
			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined is-small" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Create", class:"button is-primary is-fullwidth is-small" %>
				</div>
			</div>
			<% end %>

			<br>
		</div>
	</div>
</section>

app/views/issue/updates.html.erb
<div class="columns">
  <div class="column">
    <div class="columns">
      <div class="column">
        <%= render "/issue/tab" %>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <%= render "/layouts/updates" %>
      </div>
    </div>
  </div>
</div>

app/views/issue/view.html.erb
<div class="columns">
	<div class="column">
		<div class="columns">
			<div class="column">
				<%= render "/issue/tab" %>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<%= link_to :back, class: "button is-primary is-outlined is-small"  do %>
					<%= fa_icon "angle-left" %>&nbsp;Back
				<% end %>
				<%= link_to edit_issue_path(@record.uuid), class: "button is-primary is-outlined is-small" do %>
						<%= fa_icon "pencil" %>&nbsp;Edit issue
					<% end %>
			</div>
			<div class="column is-6">
				<p class="has-text-right has-text-weight-semibold">#<%= @record.sequence_number %></p>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<p class="has-text-weight-semibold">Details</p>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<table class="table is-striped is-fullwidth is-bordered">
					<tbody>
					<tr>
						<td style="width: 25%;">Scope</td>
						<td><%= @record.scope.title %></td>
					</tr>
					<tr>
						<td>Title</td>
						<td><%= @record.title %></td>
					</tr>
					<tr>
						<td>Score</td>
						<td><%= @record.score %></td>
					</tr>
					<tr>
						<td>Severity</td>
						<td><%= @record.severity.capitalize %></td>
					</tr>
					<tr>
						<td>Status</td>
						<td><%= @record.status.capitalize %></td>
					</tr>
					<tr>
						<td>Created At</td>
						<td><span title="<%= format_time(@record.created_at, "CET") %>"><%= distance_of_time_in_words_to_now(@record.created_at) %></span></td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Description</p>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<% if !@record.description.nil? %>
							<%= @record.description %>
						<% else %>
							...
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Solution</p>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<% if !@record.solution.nil? %>
							<%= @record.solution %>
						<% else %>
							...
						<% end %>
					</div>
				</div>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Attachments</p>
					</div>
				</div>

			<div class="columns">
				<% if @record.files.count > 0 %>
					<% @record.files.each do |file| %>
						<div class="column is-3">
							<% if file.variable? %>
								<%= image_tag file.variant(resize: "400x400") %>
							<% elsif file.previewable? %>
								<%= image_tag file.preview(resize: "400x400"), rails_blob_path(file, disposition: :attachment) %>
							<% else %>
								
							<% end %>
							<span class="tag is-gray is-medium">
								<%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
								<%= link_to 'Remove', issue_delete_attachment_path(@record.uuid, file.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
							</span>
						</div>
					<% end %>
					<% else %>
						<div class="column">
							<i>No attachments</i>
						</div>
					<% end %>
			</div>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<p class="has-text-weight-semibold">Comments</p>
			</div>
			<div class="column is-5">
				<% if @comments.length > 0 %>
					<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
				<% end %>
			</div>
		</div>
		<div class="columns">
			<div class="column">
				<table class="table is-striped is-fullwidth">
					<tbody>
					<tr>
						<td colspan="2"><%= render partial: '/issue/comment', locals: {comment: @comment, record: @record} %></td>
					</tr>
					<% if @comments.length > 0 %>
						<% @comments.each do |c| %>
							<tr>
								<td><%= c.message %></td>
								<td width="30%" class="has-text-right"><span class="is-italic has-text-small">by @<%= c.user.name.downcase %> at <%= distance_of_time_in_words_to_now(c.created_at) %> ago</span></td>
							</tr>
						<% end %>
					<% else %>
						<tr>
							<td>No comments</td>
						</tr>
					<% end %>
					</tbody>
				</table>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<h4 class="has-text-centered has-text-white-ter has-text-weight-semibold"><%= @record.uuid %></h4>
			</div>
		</div>

	</div>
</div>