config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  devise_for :users
  # devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {
  #   registrations: 'users/registrations'
  # }

  scope ActiveStorage.routes_prefix do
    get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  end

  get '/', to: 'home#index', as: 'home_page'

  get '/projects', to: 'project#index', as: 'projects_list'
  get '/projects/create', to: 'project#new', as: 'new_project'
  post '/projects/create', to: 'project#create', as: 'create_project'
  get '/projects/view/:uuid', to: 'project#view', as: 'view_project'
  get '/projects/view/:uuid/updates', to: 'project#updates', as: 'view_project_updates'
  get '/projects/edit/:uuid', to: 'project#edit', as: 'edit_project'
  patch '/projects/edit/:uuid', to: 'project#update', as: 'update_project'

  get '/scopes', to: 'scope#index', as: 'scopes_list'
  get '/scopes/create/:uuid', to: 'scope#new', as: 'new_scope'
  post '/scopes/create/:uuid', to: 'scope#create', as: 'create_scope'
  get '/scopes/view/:uuid', to: 'scope#view', as: 'view_scope'
  get '/scopes/view/:uuid/updates', to: 'scope#updates', as: 'view_scope_updates'
  get '/scopes/edit/:uuid', to: 'scope#edit', as: 'edit_scope'
  patch '/scopes/edit/:uuid', to: 'scope#update', as: 'update_scope'

  get '/issues', to: 'issue#index', as: 'issues_list'
  get '/issues/create/(:uuid)', to: 'issue#new', as: 'new_issue'
  post '/issues/create/(:uuid)', to: 'issue#create', as: 'create_issue'
  get '/issues/view/:uuid', to: 'issue#view', as: 'view_issue'
  get '/issues/view/:uuid/updates', to: 'issue#updates', as: 'view_issue_updates'
  get '/issues/edit/:uuid', to: 'issue#edit', as: 'edit_issue'
  patch '/issues/edit/:uuid', to: 'issue#update', as: 'update_issue'
  delete '/issues/a/delete/:uuid/:id', to: 'issue#delete_file', as: 'issue_delete_attachment'

  post '/comments/create/:uuid', to: 'comment#create', as: 'create_comment'
  
  get '/admin', to: 'admin/general#index', as: 'admin_general_page'
  patch '/admin/settings', to: 'admin/general#update', as: 'update_settings'
  get '/admin/users', to: 'admin/users#index', as: 'admin_users_page'
  get '/admin/users/create', to: 'admin/users#new', as: 'new_user'
  post '/admin/users/create', to: 'admin/users#create', as: 'create_user'
  get '/admin/users/edit/:uuid', to: 'admin/users#edit', as: 'edit_user'
  post '/admin/users/edit/:uuid', to: 'admin/users#update', as: 'update_user'

  get '/settings', to: 'settings#index', as: 'settings_page'
  get '/help', to: 'help#index', as: 'help_page'

end

app/models/project.rb
class Project < ApplicationRecord
	audited
	
	enum status: [:open, :closed, :ongoing, :cancelled]

	before_create :set_defaults

	has_many :scope
	belongs_to :user

	validates :title, presence: true

	
	private
	def set_defaults
		self.status ||= :open
		self.uuid = SecureRandom.uuid
	end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

	before_action :authenticate_user!
	before_action :set_record, only: [:view, :edit, :update, :updates, :delete, :delete_file]
	before_action :check_super, only: [:new, :create, :edit, :update]

	def index
		if !params[:search].blank?
			@parameter = params[:search].downcase
			@records = Project.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
		else
			@pagy, @records = pagy(Project.all, items: 2)
		end
	end

	def view
		@pagy, @records = pagy(@record.scope, items: 2)
	end

	def updates
		@updates = @record.audits.reorder(id: :desc)
	end

	def new
		@record = Project.new
	end

	def create
		@record = Project.new(request_params)
		@record.user_id = current_user.id

		if @record.valid?
			@record.save!
			redirect_to(new_scope_path(@record.uuid), notice: 'Created successfully.' )
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @record.update(request_params)
			redirect_to view_project_path(@record.uuid), notice: 'Updated successfully.'
		else
			redirect_to edit_project_path(@record.uuid), alert: 'Unable to save, try again.'
		end
	end

	def delete
		if current_user.id == @record.user_id || current_user.admin?
			@record.destroy
			if current_user.admin?
				redirect_back(fallback_location: root_path, notice: 'Deleted successfully.')
			else
				redirect_to({:controller => "home", :action => "index"}, notice: 'Deleted successfully.' )
			end
		else
			redirect_to({:action => "show", :uuid => @record.uuid}, notice: 'Unable to delete.' )
		end
	end

	private
	def set_record
		@record = Project.find_by(uuid: params[:uuid])
		if @record.nil?
			redirect_to(root_path, notice: "No record found!")
		end
	end

	def request_params
		params.require(:project).permit(:title, :description)
	end

end

app/helpers/project_helper.rb
module ProjectHelper

	def status_color(status)
		case status
		when 'open'
			return "#078080"
		when 'completed'
			return '#f45d48'
		when 'cancelled'
			return '#f45d48'
		else
			return '#000000'
		end
	end
end

app/views/project/_tab.html.erb
<div class="columns">
  <div class="column">
    <div class="tabs">
      <ul>
        <li class="<%= current(view_project_path) %>"><%= link_to "Details", view_project_path, class: "" %></li>
        <li class="<%= current(view_project_updates_path) %>"><%= link_to "Updates", view_project_updates_path, class: "" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/project/edit.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">Update project</h4>
			<hr />
			<%= simple_form_for (@record), {url: update_project_path(@record.uuid)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>
			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />
			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined is-small" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Update project", class:"button is-primary is-small" %>
				</div>
			</div>
			<% end %>

			<br>
			<p class=""></p>
		</div>
	</div>
</section>

app/views/project/index.html.erb
<div class="columns">
	<div class="column">
		<div class="columns">
			<div class="column">
				<div class="buttons">
					<% if is_super() == true %>
						<%= link_to new_project_path, class: "button is-primary is-outlined is-small" do %>
							<%= fa_icon "pencil" %>&nbsp;New project
						<% end %>
					<% end %>
				</div>
			</div>
			<div class="column is-3">
				<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
			</div>
		</div>
		<div class="columns">
			<div class="column">
				<hr />

				<div class="columns is-multiline">
					<% @records.each do |record| %>
					<div class="column is-3">
						<div class="card">
							<div class="card-content">
								<div class="content">
									<h4>
										<span style="color:  <%= status_color(record.status) %>">|</span>

										<%= truncate(record.title, length: 18) %>
									</h4>
									<p>&nbsp;<%= truncate(record.description, :length => 24) %></p>
								</div>
							</div>
							<footer class="card-footer">
								<%= link_to view_project_path(record.uuid), class: "card-footer-item" do %>
									More&nbsp;<%= fa_icon "angle-right" %>
								<% end %>
							</footer>
						</div>
					</div>
					<% end %>	
				</div>

				<div class="columns">
					<div class="column">
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/project/new.html.erb
<section class="section">
	<div class="columns">
		<div class="column is-5">
			<h4 class="title">New project</h4>
			<hr />
			<%= simple_form_for (@record), {url: create_project_path(@record)} do |f| %>
			<% if !f.error_notification.nil? %>
				<div class="field">
					<div class="control">
						<%= f.error_notification %>
					</div>
				</div>
			<% end %>
			<div class="field">
				<div class="control">
					<%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<%= f.input :description, required: false, input_html: { rows: 10, class: "textarea"}, wrapper: false, label_html: { class: "label" }, error_html: { class: "help is-danger" } %>
				</div>
			</div>
			<hr />
			<div class="field is-grouped is-grouped-right">
				<div class="control">
					<%= link_to "Cancel", :back, class: "button is-primary is-outlined is-small" %>
				</div>
				<div class="control">
					<%= f.button :submit, "Create project", class:"button is-primary is-small" %>
				</div>
			</div>
			<% end %>

			<br>
			<p class=""></p>
		</div>
	</div>
</section>

app/views/project/updates.html.erb
<div class="columns">
  <div class="column">
    <div class="columns">
      <div class="column">
        <%= render "/project/tab" %>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <%= render "/layouts/updates" %>
      </div>
    </div>
  </div>
</div>

app/views/project/view.html.erb
<div class="columns">
	<div class="column">

		<div class="columns">
			<div class="column">
				<%= render "/project/tab" %>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<%= link_to new_scope_path(uuid: @record.uuid), class: "button is-primary is-outlined is-small"  do %>
					<%= fa_icon "pencil" %>&nbsp;Add scope
				<% end %>
				<%= link_to edit_project_path(@record.uuid), class: "button is-primary is-outlined is-small" do %>
					<%= fa_icon "pencil" %>&nbsp;Edit project
				<% end %>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<div class="columns">
					<div class="column">
						<p class="has-text-weight-semibold">Details</p>
					</div>
					<div class="column is-5">
						<% if @record.scope.length > 0 %>
							<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
						<% end %>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<table class="table is-fullwidth is-striped is-bordered">
							<tbody>
								<tr>
									<td style="width: 25%">Title</td>
									<td><%= @record.title %></td>
								</tr>
								<tr>
									<td>Status</td>
									<td><%= @record.status.capitalize %></td>
								</tr>
								<tr>
									<td>Description</td>
									<td><%= @record.description %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="columns">
					<div class="column">
						<hr />
						<div class="columns">
							<div class="column">
								<p class="has-text-weight-semibold">Scopes</p>
							</div>
							<div class="column is-3">
								<%= render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
							</div>
						</div>
						<div class="columns">
							<div class="column">
								<% if @record.scope.length > 0 %>
								<table class="table is-striped is-fullwidth is-bordered">
									<thead>
										<tr>
											<th style="width: 36px;"></th>
											<th>Title</th>
											<th style="width: 40px;">Version</th>
											<th style="width: 36px;"></th>
										</tr>
									</thead>
									<tbody>
										<% @records.each do |s| %>
										<tr>
											<td><%= fa_icon "folder" %></td>
											<td><%= s.title %></td>
											<td><%= s.version %></td>
											<td class="level-right">
												<%= link_to view_scope_path(s.uuid)  do %>
												<%= fa_icon "folder-open-o" %>
												<% end %>
											</td>
										</tr>
										<% end %>
									</tbody>
								</table>
								<% else %>
									<div class="columns">
										<div class="column">
											<h4>No scopes.</h4>
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>