config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  devise_for :users
  # devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {
  #   registrations: 'users/registrations'
  # }

  scope ActiveStorage.routes_prefix do
    get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  end

  get '/', to: 'home#index', as: 'home_page'

  get '/projects', to: 'project#index', as: 'projects_list'
  get '/projects/create', to: 'project#new', as: 'new_project'
  post '/projects/create', to: 'project#create', as: 'create_project'
  get '/projects/view/:uuid', to: 'project#view', as: 'view_project'
  get '/projects/view/:uuid/updates', to: 'project#updates', as: 'view_project_updates'
  get '/projects/edit/:uuid', to: 'project#edit', as: 'edit_project'
  patch '/projects/edit/:uuid', to: 'project#update', as: 'update_project'

  get '/scopes', to: 'scope#index', as: 'scopes_list'
  get '/scopes/create/:uuid', to: 'scope#new', as: 'new_scope'
  post '/scopes/create/:uuid', to: 'scope#create', as: 'create_scope'
  get '/scopes/view/:uuid', to: 'scope#view', as: 'view_scope'
  get '/scopes/view/:uuid/updates', to: 'scope#updates', as: 'view_scope_updates'
  get '/scopes/edit/:uuid', to: 'scope#edit', as: 'edit_scope'
  patch '/scopes/edit/:uuid', to: 'scope#update', as: 'update_scope'

  get '/issues', to: 'issue#index', as: 'issues_list'
  get '/issues/create/(:uuid)', to: 'issue#new', as: 'new_issue'
  post '/issues/create/(:uuid)', to: 'issue#create', as: 'create_issue'
  get '/issues/view/:uuid', to: 'issue#view', as: 'view_issue'
  get '/issues/view/:uuid/updates', to: 'issue#updates', as: 'view_issue_updates'
  get '/issues/edit/:uuid', to: 'issue#edit', as: 'edit_issue'
  patch '/issues/edit/:uuid', to: 'issue#update', as: 'update_issue'
  delete '/issues/a/delete/:uuid/:id', to: 'issue#delete_file', as: 'issue_delete_attachment'

  post '/comments/create/:uuid', to: 'comment#create', as: 'create_comment'
  
  get '/admin', to: 'admin/general#index', as: 'admin_general_page'
  patch '/admin/settings', to: 'admin/general#update', as: 'update_settings'
  get '/admin/users', to: 'admin/users#index', as: 'admin_users_page'
  get '/admin/users/create', to: 'admin/users#new', as: 'new_user'
  post '/admin/users/create', to: 'admin/users#create', as: 'create_user'
  get '/admin/users/edit/:uuid', to: 'admin/users#edit', as: 'edit_user'
  post '/admin/users/edit/:uuid', to: 'admin/users#update', as: 'update_user'

  get '/settings', to: 'settings#index', as: 'settings_page'
  get '/help', to: 'help#index', as: 'help_page'

end

app/views/layouts/_pagination.html.erb
<nav class="pagination is-centered is-small" role="navigation" aria-label="pagination">
	<%= link_to "Previous", projects_list_path(page: @page - 1), class: "pagination-previous" %>
	<%= link_to "Next page", projects_list_path(page: @page + 1), class: "pagination-next" %>
</nav>

app/views/layouts/_updates.html.erb
<% @updates.each do |r| %>
  <div class="updates">
    <div>
      Record
      <% if r.action == "create" %>
        created
      <% elsif r.action == "update" %>
        updated
      <% end %>
      <span title="<%= format_time(@record.created_at, "CET") %>"><%= distance_of_time_in_words_to_now(r.created_at) %>
        ago</span>
      by <%= r.user.name %>
    </div>
    <div class="fields">
      <% if r.action == "update" %>
        <% r.audited_changes.each do |a| %>
          <div>
            <b><%= a[0].titleize %></b>
            from <i><%= a[1][0] %></i> to <i><%= a[1][1] %></i>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag asset_path('favicon-32x32.png') %>
  <title>Project Longhall</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <nav class="navbar is-white" role="navigation" aria-label="main navigation">
    <div class="container is-max-desktop">
      <div class="navbar-brand">
        <%= link_to home_page_path, class: "navbar-item #{current(home_page_path)}" do %>
          <%= fa_icon "bolt" %>
        <% end %>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <% if user_signed_in? %>
            <%= link_to projects_list_path, class: "navbar-item #{current(projects_list_path)}" do %>Projects
            <% end %>
            <%= link_to issues_list_path, class: "navbar-item #{current(issues_list_path)}" do %>Issues
            <% end %>
          <% end %>
        </div>

        <div class="navbar-end">
          <% if user_signed_in? %>
            <%= link_to new_issue_path, class: "navbar-item #{current(new_issue_path)}" do %>New issue
            <% end %>
          <% end %>

          <%= link_to help_page_path, class: "navbar-item #{current(help_page_path)}" do %>
            <%= fa_icon "question-circle" %>
          <% end %>

          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <%= link_to "Adminland", admin_general_page_path, class: "navbar-item #{current(admin_general_page_path)}" %>
            <% end %>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <p>Hello!</p>
              </a>

              <div class="navbar-dropdown is-right">
                <%= link_to "Change password", edit_user_path(current_user.uuid), class: "navbar-item #{current(settings_page_path)}" %>
                <hr class="navbar-divider">
                <%= link_to destroy_user_session_path, method: :delete, class: "navbar-item" do %>
                  <%= fa_icon "power-off" %>&nbsp;Log Out
                <% end %>
              </div>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "navbar-item" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container is-max-desktop" style="margin-top: 10px;">
    <div class="columns is-centered">
      <div class="column is-10">
        <% if flash[:notice] %>
          <div class="notification is-primary global-notification">
            <p><%= notice %></p>
          </div>
        <% end %>
        <% if flash[:errors] %>
          <% flash[:errors].each do |error| %>
            <div class="notification is-danger global-notification">
              <p><%= error %></p>
            </div>
          <% end %>
        <% end %>
        <% if flash[:alert] %>
          <div class="notification is-warning global-notification">
            <p><%= alert %></p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="columns inner-background">
      <div class="column">
        <%= yield %>
      </div>
    </div>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="content has-text-centered">
        <small>
          The source code is licensed
          <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
          is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </small>
      </div>
    </footer>
  </div>
</body>
</html>